FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
EXPOSE 9001
CMD ["uvicorn", "app.exporter:app", "--host", "0.0.0.0", "--port", "9001"]
