# In file: .github/workflows/ci.yml

name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Extra packages used by the backtester
          pip install yfinance vectorbt duckdb
      
      # --- THIS IS THE NEW STEP ---
      # It installs ruff and runs it to check for style issues.
      # The '--check' flag means it will fail if the code is not formatted correctly.
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check .

      # --- This step remains the same ---
      - name: Run PyTest suite
        run: |
          python -m pytest

      # --- Add C++ unit tests ---
      - name: Configure and run CTest
        run: |
          cmake -S cpp -B build
          ctest --test-dir build -j2 --output-on-failure

